---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd   # don't confuse the target namespace (1-deployment) with the argoCD application namespace
                      # the namescpace here is always "argocd"
spec:
  project: default    # Projects provide a logical grouping of applications, which is useful when Argo CD is used by multiple teams
  source:
    repoURL: git@github.com:ppagnoni/monnezza.git # we are using a public repo, we can use both ssh or https
    targetRevision: HEAD  # we can use git brnaches or tags and also regx expressions
                          # in case of it should point to the chart version
    path: "ArgoCD Tutorial for Beginners: GitOps CD for Kubernetes #1/01_example/"
  destination:
    server: https://kubernetes.default.svc

    # The destination is useful when you use a single argocd instance to deploy applications to multiple clusters. 
    # In our case, we'll deploy the app to the same Kubernetes cluster where argocd is running, so we need to provide a path to the local Kubernetes api server. 
    # That's the bare minimum that we need to get started with argocd.