---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-2
  namespace: argocd   # don't confuse the target namespace (1-deployment) with the argoCD application namespace
                      # the namescpace here is always "argocd"
  finalizers:
    # - resources-finalizer.argocd.argoproj.io  # delete the resource in the cluster when the app is deleted by cli
      # the option above trigger a warning when apply this app: prefer a domain-qualified finalizer name including a path (/) to avoid accidental conflicts with other finalizer writers
      # 🚨 https://codefresh.io/blog/argocd-application-deletion-finalizers/
      # 🚨 https://github.com/argoproj/argo-cd/issues/21035
      # 🚨 https://github.com/argoproj/argo-cd/issues/22346
    - "resources-finalizer.argocd.argoproj.io/background"
spec:
  project: default    # Projects provide a logical grouping of applications, which is useful when Argo CD is used by multiple teams
  source:
    repoURL: https://github.com/ppagnoni/monnezza.git # we are using a public repo, we can use both ssh or https
    targetRevision: HEAD  # we can use git brnaches or tags and also regx expressions
                          # in case of it should point to the chart version
    path: "ArgoCD Tutorial for Beginners: GitOps CD for Kubernetes n1/01_example"
  destination:
    server: https://kubernetes.default.svc   # this is the api-server service!!!

    # The destination is useful when you use a single argocd instance to deploy applications to multiple clusters. 
    # In our case, we'll deploy the app to the same Kubernetes cluster where argocd is running, so we need to provide a path to the local Kubernetes api server. 
    # That's the bare minimum that we need to get started with argocd.

  # 🚨 https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/
  # 🚨 https://argo-cd.readthedocs.io/en/latest/user-guide/sync-options/
  # 🚨 https://codefresh.io/learn/argo-cd/argocd-sync-policies-a-practical-guide/
  syncPolicy:   # manages the synchronization of applications deployed in a Kubernetes environment with their corresponding configurations stored in a Git repository. 
    automated:
      prune: true   # By default (and as a safety mechanism), automated sync will not delete resources when Argo CD detects the resource is no longer defined in Git
      selfHeal: true   # automatically sync differences in the live cluster state and the Git-defined state (git is source of truth)
      allowEmpty: false   # ???
    syncOptions:
      - Validate=true   # if a manifes has an unknown field it will be rejected by ArgoCD (Validate=true is the default) 
      - CreateNamespace=false   # similar to helm chart it define if you want to create the namespace
      - PrunePropagationPolicy=foreground   # ???
      - PruneLast=true   # ???